name: Test Trigger

on:
  push:      # Сработает при любом пуше в любую ветку
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "I am alive!"
