name: Test Trigger

on:
  push:
    tags:
      - '*'
  workflow_dispatch: # Добавляет кнопку ручного запуска

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered!"